Reorder csu commands to be alphabetically sorted

diff --git a/csu b/csu
--- a/csu
+++ b/csu
@@ -10,14 +10,16 @@
 # Future plans:
 #  - Start systems when a command is given (for example: 'static') when the
 #    development system has not yet been started.
-#  - When 'start' is run open website in default browser without creating
-#    new terminal prompt.
 
 set -e
 
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 NC='\033[0m' # No Color
+
+###############################################################################
+# HELP TEXT LOGIC
+###############################################################################
 
 cmd_helps=()
 dev_cmd_helps=()
@@ -38,26 +40,51 @@ defhelp() {
   fi
 }
 
-# Print out help information
-cmd_help() {
-  echo "Script for performing tasks related to the CS Unplugged repository."
-  echo
-  echo "Usage: ./csu [COMMAND]"
-  echo "Replace [COMMAND] with a word from the list below."
-  echo
-  echo "COMMAND list:"
-  for str in "${cmd_helps[@]}"; do
-    echo -e "$str"
-  done
-  echo
-  echo "DEV_COMMAND list:"
-  for str in "${dev_cmd_helps[@]}"; do
-    echo -e "$str"
-  done
-}
+###############################################################################
+# BASIC COMMANDS
+###############################################################################
 
+# Delete all untagged dangling Docker images
+cmd_clean() {
+  echo "If the following commands return an argument not found error,"
+  echo "this is because there is nothing to delete for clean up."
+
+  echo
+  echo "Deleting unused volumes..."
+  docker volume ls -qf dangling=true | xargs -r docker volume rm
+  echo
+  echo "Deleting exited containers..."
+  docker ps --filter status=dead --filter status=exited -aq | xargs docker rm -v
+  echo
+  echo "Deleting dangling images..."
+  docker images -f "dangling=true" -q | xargs docker rmi
+}
+defhelp clean 'Delete unused Docker files.'
+
+# Stop development environment
+cmd_end() {
+  echo "Stopping systems... (takes roughly 10 to 20 seconds)"
+  docker-compose down
+  echo
+  echo "Deleting system volumes..."
+  docker volume ls -qf dangling=true | xargs -r docker volume rm
+}
+defhelp end 'Stop development environment.'
+
+# Display help command here for alphabetical order
 defhelp help 'View all help.'
-defhelp 'dev [DEV_COMMAND]' 'Run a developer command.'
+
+# View logs
+cmd_logs() {
+  docker-compose logs
+}
+defhelp logs 'View logs.'
+
+cmd_restart() {
+  cmd_end
+  cmd_start
+}
+defhelp restart 'Stop and then restart development environment.'
 
 # Start development environment
 cmd_start() {
@@ -70,24 +97,7 @@ cmd_start() {
   echo -e "\n${GREEN}Systems are ready!${NC}"
   echo "Open your preferred web browser to the URL 'localhost'"
 }
-
 defhelp start 'Start development environment (this also runs the update command).'
-
-# Stop development environment
-cmd_end() {
-  echo "Stopping systems... (takes roughly 10 to 20 seconds)"
-  docker-compose down
-  echo
-  echo "Deleting system volumes..."
-  docker volume ls -qf dangling=true | xargs -r docker volume rm
-}
-defhelp end 'Stop development environment.'
-
-cmd_restart() {
-  cmd_end
-  cmd_start
-}
-defhelp restart 'Stop and then restart development environment.'
 
 # Run Django migrate and updatedata commands
 cmd_update() {
@@ -106,6 +116,30 @@ cmd_update() {
 }
 defhelp update 'Run Django migrate and updatedata commands and build static files.'
 
+# Delete all Docker containers and images
+cmd_wipe() {
+  docker ps -a -q | xargs docker rm
+  docker images -q | xargs docker rmi
+}
+defhelp wipe 'Delete all Docker containers and images.'
+
+# Display dev help text at end of basic command list
+defhelp 'dev [DEV_COMMAND]' 'Run a developer command.'
+
+###############################################################################
+# DEVELOPER COMMANDS
+###############################################################################
+
+# Build Docker images
+dev_build() {
+  echo "Building Docker images..."
+  docker-compose build
+  echo
+  echo "Deleting untagged images..."
+  docker images --no-trunc | grep '<none>' | awk '{ print $3 }' | xargs -r docker rmi
+}
+defhelp -dev build 'Build or rebuild Docker images.'
+
 # Collecting static files
 dev_collect_static() {
   echo
@@ -113,6 +147,17 @@ dev_collect_static() {
   docker-compose exec django /docker_venv/bin/python3 ./manage.py collectstatic --no-input --clear
 }
 defhelp -dev collect_static "Collecting static files."
+
+# Generates the documentation (with warnings as errors)
+dev_docs() {
+  echo "Removing any existing documentation..."
+  docker-compose exec django rm -rf /cs-unplugged/docs/build/
+  docker-compose exec django mkdir /cs-unplugged/docs/build/
+  echo
+  echo "Creating documentation..."
+  docker-compose exec django /docker_venv/bin/sphinx-build -W /cs-unplugged/docs/source/ /cs-unplugged/docs/build/
+}
+defhelp -dev docs 'Generate documentation.'
 
 # Run Django flush command
 dev_flush() {
@@ -148,22 +193,18 @@ dev_migrate() {
 }
 defhelp -dev migrate 'Run Django migrate command.'
 
-# Run Django updatedata command
-dev_updatedata() {
-  echo "Loading content..."
-  docker-compose exec django /docker_venv/bin/python3 ./manage.py updatedata
+# Reboot Django Docker container
+dev_reboot_django() {
+  echo "Rebooting Django Docker container..."
+  docker-compose up -d django
 }
-defhelp -dev updatedata 'Run updatedata command.'
+defhelp -dev reboot_django 'Reboot Django Docker container.'
 
-# Build Docker images
-dev_build() {
-  echo "Building Docker images..."
-  docker-compose build
-  echo
-  echo "Deleting untagged images..."
-  docker images --no-trunc | grep '<none>' | awk '{ print $3 }' | xargs -r docker rmi
+# Run shell
+dev_shell() {
+  docker-compose exec django bash
 }
-defhelp -dev build 'Build or rebuild Docker images.'
+defhelp -dev shell "Open shell to Django folder."
 
 # Build static files
 dev_static() {
@@ -186,19 +227,6 @@ dev_static_scratch() {
 }
 defhelp -dev static_scratch "Build scratch images."
 
-# Run shell
-dev_shell() {
-  docker-compose exec django bash
-}
-defhelp -dev shell "Open shell to Django folder."
-
-# Reboot Django Docker container
-dev_reboot_django() {
-  echo "Rebooting Django Docker container..."
-  docker-compose up -d django
-}
-defhelp -dev reboot_django 'Reboot Django Docker container.'
-
 # Run style checks
 dev_style() {
   echo "Running PEP8 style checker..."
@@ -212,6 +240,28 @@ dev_style() {
 }
 defhelp -dev style 'Run style checks.'
 
+# Run test suite backwards for CI testing
+dev_test_backwards() {
+  echo "Running test suite backwards..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py test --settings=config.settings.testing --pattern "test_*.py" --reverse -v 0
+}
+defhelp -dev test_backwards 'Run test suite backwards.'
+
+# Display test coverage table
+dev_test_coverage() {
+  echo "Displaying test suite coverage..."
+  docker-compose exec django /docker_venv/bin/coverage xml -i
+  docker-compose exec django /docker_venv/bin/coverage report -m --skip-covered
+}
+defhelp -dev test_coverage 'Display code coverage report.'
+
+# Run specific test suite
+dev_test_specific() {
+  echo "Running specific test suite..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py test --settings=config.settings.testing "${1}" -v 3 --nomigrations
+}
+defhelp -dev test_specific 'Run specific test suite. Pass in parameter of Python test module.'
+
 # Run test suite
 dev_test_suite() {
   echo "Running test suite..."
@@ -223,87 +273,38 @@ dev_test_suite() {
 }
 defhelp -dev test_suite 'Run test suite with code coverage.'
 
-# Run specific test suite
-dev_test_specific() {
-  echo "Running specific test suite..."
-  docker-compose exec django /docker_venv/bin/python3 ./manage.py test --settings=config.settings.testing "${1}" -v 3 --nomigrations
+# Run Django updatedata command
+dev_updatedata() {
+  echo "Loading content..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py updatedata
 }
-defhelp -dev test_specific 'Run specific test suite. Pass in parameter of Python test module.'
-
-# Display test coverage table
-dev_test_coverage() {
-  echo "Displaying test suite coverage..."
-  docker-compose exec django /docker_venv/bin/coverage xml -i
-  docker-compose exec django /docker_venv/bin/coverage report -m --skip-covered
-}
-defhelp -dev test_coverage 'Display code coverage report.'
-
-# Run test suite backwards for CI testing
-dev_test_backwards() {
-  echo "Running test suite backwards..."
-  docker-compose exec django /docker_venv/bin/python3 ./manage.py test --settings=config.settings.testing --pattern "test_*.py" --reverse -v 0
-}
-defhelp -dev test_backwards 'Run test suite backwards.'
-
-# Generates the documentation (with warnings as errors)
-dev_docs() {
-  echo "Removing any existing documentation..."
-  docker-compose exec django rm -rf /cs-unplugged/docs/build/
-  docker-compose exec django mkdir /cs-unplugged/docs/build/
-  echo
-  echo "Creating documentation..."
-  docker-compose exec django /docker_venv/bin/sphinx-build -W /cs-unplugged/docs/source/ /cs-unplugged/docs/build/
-}
-defhelp -dev docs 'Generate documentation.'
+defhelp -dev updatedata 'Run updatedata command.'
 
 # Generates the documentation (with warnings as errors)
 dev_validate_templates() {
   echo "Checking templates..."
   docker-compose exec django /docker_venv/bin/python3 ./manage.py validate_templates
 }
-defhelp -dev docs 'Checks templates for syntax or compile errors.'
+defhelp -dev validate_templates 'Checks templates for syntax or compile errors.'
 
-# Delete all untagged dangling Docker images
-cmd_clean() {
-  echo "If the following commands return an argument not found error,"
-  echo "this is because there is nothing to delete for clean up."
+###############################################################################
+# CONTINUOUS INTEGRATION COMMANDS
+###############################################################################
 
-  echo
-  echo "Deleting unused volumes..."
-  docker volume ls -qf dangling=true | xargs -r docker volume rm
-  echo
-  echo "Deleting exited containers..."
-  docker ps --filter status=dead --filter status=exited -aq | xargs docker rm -v
-  echo
-  echo "Deleting dangling images..."
-  docker images -f "dangling=true" -q | xargs docker rmi
+ci_docs() {
+  dev_docs
 }
-defhelp clean 'Delete unused Docker files.'
 
-# Delete all Docker containers and images
-cmd_wipe() {
-  docker ps -a -q | xargs docker rm
-  docker images -q | xargs docker rmi
+ci_style() {
+  dev_style
 }
-defhelp wipe 'Delete all Docker containers and images.'
 
-# View logs
-cmd_logs() {
-  docker-compose logs
+ci_test_backwards() {
+  dev_test_backwards
 }
-defhelp logs 'View logs.'
 
 ci_test_general() {
   docker-compose exec django /docker_venv/bin/coverage run --rcfile=/cs-unplugged/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --exclude-tag=resource --exclude-tag=management
-  test_status=$?
-  dev_test_coverage
-  coverage_status=$?
-  bash <(curl -s https://codecov.io/bash)
-  ! (( $test_status || $coverage_status ))
-}
-
-ci_test_resources() {
-  docker-compose exec django /docker_venv/bin/coverage run --rcfile=/cs-unplugged/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --tag=resource
   test_status=$?
   dev_test_coverage
   coverage_status=$?
@@ -320,20 +321,39 @@ ci_test_management() {
   ! (( $test_status || $coverage_status ))
 }
 
-ci_style() {
-  dev_style
-}
-
-ci_test_backwards() {
-  dev_test_backwards
-}
-
-ci_docs() {
-  dev_docs
+ci_test_resources() {
+  docker-compose exec django /docker_venv/bin/coverage run --rcfile=/cs-unplugged/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --tag=resource
+  test_status=$?
+  dev_test_coverage
+  coverage_status=$?
+  bash <(curl -s https://codecov.io/bash)
+  ! (( $test_status || $coverage_status ))
 }
 
 ci_validate_templates() {
   dev_validate_templates
+}
+
+###############################################################################
+# SCRIPT LOGIC
+###############################################################################
+
+# Print out help information
+cmd_help() {
+  echo "Script for performing tasks related to the CS Unplugged repository."
+  echo
+  echo "Usage: ./csu [COMMAND]"
+  echo "Replace [COMMAND] with a word from the list below."
+  echo
+  echo "COMMAND list:"
+  for str in "${cmd_helps[@]}"; do
+    echo -e "$str"
+  done
+  echo
+  echo "DEV_COMMAND list:"
+  for str in "${dev_cmd_helps[@]}"; do
+    echo -e "$str"
+  done
 }
 
 cmd_ci() {
