(WIP) Update traefik configuation
TODO
- Fix CORS issue with some files

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -44,6 +44,11 @@ cmd_help() {
 }
 defhelp help 'View all help.'
 
+cmd_setup_https() {
+  mkdir -p infrastructure/local/traefik/certs/
+  mkcert -cert-file infrastructure/local/traefik/certs/local-cert.pem -key-file infrastructure/local/traefik/certs/local-key.pem "cs-unplugged.localhost" "*.cs-unplugged.localhost"
+}
+
 # Start development environment
 cmd_start() {
   echo "Creating systems..."
@@ -62,10 +67,9 @@ cmd_end() {
 defhelp end 'Stop development environment.'
 
 cmd_restart() {
-  cmd_end
-  cmd_start
+  docker-compose -f docker-compose.local.yml restart "$@"
 }
-defhelp restart 'Stop and then restart development environment.'
+defhelp restart 'Restart container.'
 
 # Update all content
 cmd_update() {
@@ -75,15 +79,15 @@ cmd_update() {
   cmd_migrate
 
   echo ""
-  cmd_updatedata
+  cmd_update_data
 
   cmd_rebuild_index
   echo ""
-  cmd_makeresourcethumbnails
+  cmd_make_resource_thumbnails
   cmd_collect_static
   echo ""
   echo -e "\n${SUCCESS}Content is loaded!${NC}"
-  echo "Open your preferred web browser to the URL 'localhost'"
+  echo "Open your preferred web browser to the URL 'cs-unplugged.localhost'"
 }
 defhelp update 'Run Django migrate and updatedata commands and build static files.'
 
@@ -109,17 +113,32 @@ cmd_reboot_django() {
 defhelp reboot_django 'Reboot Django container.'
 
 # Run Django updatedata command
-cmd_updatedata() {
+cmd_update_data() {
   echo "Loading content..."
   docker-compose -f docker-compose.local.yml run --rm django python ./manage.py updatedata
 }
 defhelp updatedata 'Load content into database.'
 
+# Build static files
+cmd_static() {
+  echo "Building static files..."
+  docker-compose -f docker-compose.local.yml run --rm node npm run dev
+}
+defhelp static 'Build static files.'
+
+# Collecting static files
+cmd_collect_static() {
+  echo
+  echo "Collecting static files..."
+  docker-compose -f docker-compose.local.yml run --rm django python manage.py collectstatic --no-input --clear
+}
+defhelp collect_static "Collecting static files."
+
 # Update and collect static files
 cmd_update_static() {
-  docker-compose -f docker-compose.local.yml up node
+  cmd_static
   echo ""
-  docker-compose -f docker-compose.local.yml run --rm django python manage.py collectstatic --no-input --clear
+  cmd_collect_static
   echo ""
   echo -e "\n${SUCCESS}Static files are updated!${NC}"
 }
@@ -153,12 +172,105 @@ cmd_build() {
 }
 defhelp build 'Build or rebuild Docker images.'
 
+# Run shell
+cmd_exec() {
+  docker-compose -f docker-compose.local.yml exec "$@"
+}
+defhelp shell "Execute command in given container."
+
 # View Docker logs
 cmd_logs() {
   echo "Building Docker images..."
   docker-compose -f docker-compose.local.yml logs --timestamps "$@"
 }
 defhelp build 'View logs.'
+
+# Run style checks
+cmd_style() {
+  echo "Running PEP8 style checker..."
+  docker-compose -f docker-compose.local.yml run --rm django flake8
+  pep8_status=$?
+  echo
+  echo "Running Python docstring checker..."
+  docker-compose -f docker-compose.local.yml run --rm django pydocstyle --count --explain
+  pydocstyle_status=$?
+  ! (( pep8_status || pydocstyle_status ))
+}
+defhelp style 'Run style checks.'
+
+# Run test suite
+cmd_test_suite() {
+  echo "Running test suite..."
+  docker-compose -f docker-compose.local.yml run --rm django coverage run --rcfile=/cs-unplugged/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --nomigrations
+}
+defhelp test_suite 'Run test suite with code coverage.'
+
+# Run specific test suite
+cmd_test_specific() {
+  echo "Running specific test suite..."
+  docker-compose -f docker-compose.local.yml run --rm django python ./manage.py test --settings=config.settings.testing "${1}" -v 3 --nomigrations
+}
+defhelp test_specific 'Run specific test suite. Pass in parameter of Python test module.'
+
+# Display test coverage table
+cmd_test_coverage() {
+  echo "Displaying test suite coverage..."
+  docker-compose -f docker-compose.local.yml run --rm django coverage xml -i
+  docker-compose -f docker-compose.local.yml run --rm django coverage report -m --skip-covered
+}
+defhelp test_coverage 'Display code coverage report.'
+
+# Run test suite backwards for CI testing
+cmd_test_backwards() {
+  echo "Running test suite backwards..."
+  docker-compose -f docker-compose.local.yml run --rm django python ./manage.py test --settings=config.settings.testing --pattern "test_*.py" --reverse -v 0 --nomigrations
+}
+defhelp test_backwards 'Run test suite backwards.'
+
+cmd_createsuperuser() {
+  docker-compose -f docker-compose.local.yml run --rm django python ./manage.py createsuperuser
+}
+defhelp createsuperuser "Create superuser in Django system."
+
+# --- Testing -----------------------------------------------------------------
+
+cmd_ci() {
+  cmd_start
+  cmd_static
+  cmd_collect_static
+  local cmd="$1"
+  shift
+  if [ -z "$cmd" ]; then
+    echo -e "${ERROR}ERROR: test command requires one parameter!${NC}"
+    cmd_help
+    exit 1
+  fi
+  if silent type "cmd_$cmd"; then
+    "cmd_$cmd" "$@"
+    test_status=$?
+    cmd_test_coverage
+    coverage_status=$?
+    exit $test_status || $coverage_status
+  else
+    echo -e "${ERROR}ERROR: Unknown command!${NC}"
+    echo "Type './dev help' for available commands."
+    exit 1
+  fi
+}
+
+cmd_test_general() {
+  docker-compose -f docker-compose.local.yml run --rm django coverage run --rcfile=./.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --exclude-tag=resource --exclude-tag=management --nomigrations
+}
+
+cmd_test_resources() {
+  docker-compose -f docker-compose.local.yml run --rm django coverage run --rcfile=/cs-unplugged/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --tag=resource --nomigrations
+  test_status=$?
+}
+
+cmd_test_management() {
+  docker-compose -f docker-compose.local.yml run --rm django coverage run --rcfile=/cs-unplugged/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --tag=management --nomigrations
+  test_status=$?
+}
 
 # --- Core script logic -------------------------------------------------------
 
@@ -179,6 +291,6 @@ if silent type "cmd_$cmd"; then
   exit $?
 else
   echo -e "${ERROR}ERROR: Unknown command!${NC}"
-  echo "Type './csu help' for available commands."
+  echo "Type './dev help' for available commands."
   exit 1
 fi
